### ISSUE TITLE
MetaCPAN points to RT for issues?

### ISSUE THREAD

**Issue by djzort** [zorgnax/dbilog#13]
Take a look at https://metacpan.org/pod/DBI::Log the issues link points to RT

I dont know if thats intended.

**Comment by djzort** [comment]
This distro isnt using Dist::Zilla so i cant quickly send a PR to point "issues" to github

**Comment by zorgnax** [comment]
I think metacpan.org adds that by itself and I can't control it, I might be able to by setting something in the Makefile.PL but not sure what. I don't want to use Dist::Zilla because it's just too much. I already have to know about ExtUtils::MakeMaker when I make the Makefile.PL, and I know there's another one called Module::Build used in Build.PL, and Dist::Zilla is this other thing but it goes on top of those things, I just want to stick with the Makefile.PL it's good enough. I tried installing Dist::Zilla once, and it adds an insane number of dependencies.

**Comment by djzort** [comment]
RT is the default. You can provide the bugtracker in the META.yml file https://metacpan.org/pod/CPAN::Meta::Spec
